In [75]:
import pandas as pd
import numpy as np

In [76]:
breast_ds=pd.read_csv("data.csv")
breast_ds.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [77]:
breast_ds['diagnosis'].value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

In [78]:
breast_ds.shape

(569, 33)

In [79]:
breast_ds.isnull().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed: 32                569
dtype: int64

In [80]:
breast_ds.duplicated().sum()

np.int64(0)

In [81]:
breast_ds.info()

<class 'pandas.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       569 non-null    int64
 1   diagnosis                569 non-null    str
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             569 non-null    float64
 15  area_se                  569 non-null    float64
 16  smoothness_se            569 non-null    float64
 17  compactness_se           569 non-null    float64
 18  concavity_se             569 non-null    float64
 19  concave points_se        569 non-null    float64
 20  symmetry_se              569 non-null    float64
 21  fractal_dimension_se     569 non-null    float64
 22  radius_worst             569 non-null    float64
 23  texture_worst            569 non-null    float64
 24  perimeter_worst          569 non-null    float64
 25  area_worst               569 non-null    float64
 26  smoothness_worst         569 non-null    float64
 27  compactness_worst        569 non-null    float64
 28  concavity_worst          569 non-null    float64
 29  concave points_worst     569 non-null    float64
 30  symmetry_worst           569 non-null    float64
 31  fractal_dimension_worst  569 non-null    float64
 32  Unnamed: 32              0 non-null      float64
dtypes: float64(31), int64(1), str(1)
memory usage: 147.4 KB

In [82]:
breast_ds.corr(numeric_only=True)

,id,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
id,1.000000,0.074626,0.099770,0.073159,0.096893,-0.012968,0.000096,0.050080,0.044158,-0.022114,...,0.064720,0.079986,0.107187,0.010338,-0.002968,0.023203,0.035174,-0.044224,-0.029866,NaN
radius_mean,0.074626,1.000000,0.323782,0.997855,0.987357,0.170581,0.506124,0.676764,0.822529,0.147741,...,0.297008,0.965137,0.941082,0.119616,0.413463,0.526911,0.744214,0.163953,0.007066,NaN
texture_mean,0.099770,0.323782,1.000000,0.329533,0.321086,-0.023389,0.236702,0.302418,0.293464,0.071401,...,0.912045,0.358040,0.343546,0.077503,0.277830,0.301025,0.295316,0.105008,0.119205,NaN
perimeter_mean,0.073159,0.997855,0.329533,1.000000,0.986507,0.207278,0.556936,0.716136,0.850977,0.183027,...,0.303038,0.970387,0.941550,0.150549,0.455774,0.563879,0.771241,0.189115,0.051019,NaN
area_mean,0.096893,0.987357,0.321086,0.986507,1.000000,0.177028,0.498502,0.685983,0.823269,0.151293,...,0.287489,0.959120,0.959213,0.123523,0.390410,0.512606,0.722017,0.143570,0.003738,NaN
smoothness_mean,-0.012968,0.170581,-0.023389,0.207278,0.177028,1.000000,0.659123,0.521984,0.553695,0.557775,...,0.036072,0.238853,0.206718,0.805324,0.472468,0.434926,0.503053,0.394309,0.499316,NaN
compactness_mean,0.000096,0.506124,0.236702,0.556936,0.498502,0.659123,1.000000,0.883121,0.831135,0.602641,...,0.248133,0.590210,0.509604,0.565541,0.865809,0.816275,0.815573,0.510223,0.687382,NaN
concavity_mean,0.050080,0.676764,0.302418,0.716136,0.685983,0.521984,0.883121,1.000000,0.921391,0.500667,...,0.299879,0.729565,0.675987,0.448822,0.754968,0.884103,0.861323,0.409464,0.514930,NaN
concave points_mean,0.044158,0.822529,0.293464,0.850977,0.823269,0.553695,0.831135,0.921391,1.000000,0.462497,...,0.292752,0.855923,0.809630,0.452753,0.667454,0.752399,0.910155,0.375744,0.368661,NaN
symmetry_mean,-0.022114,0.147741,0.071401,0.183027,0.151293,0.557775,0.602641,0.500667,0.462497,1.000000,...,0.090651,0.219169,0.177193,0.426675,0.473200,0.433721,0.430297,0.699826,0.438413,NaN
fractal_dimension_mean,-0.052511,-0.311631,-0.076437,-0.261477,-0.283110,0.584792,0.565369,0.336783,0.166917,0.479921,...,-0.051269,-0.205151,-0.231854,0.504942,0.458798,0.346234,0.175325,0.334019,0.767297,NaN
radius_se,0.143048,0.679090,0.275869,0.691765,0.732562,0.301467,0.497473,0.631925,0.698050,0.303379,...,0.194799,0.719684,0.751548,0.141919,0.287103,0.380585,0.531062,0.094543,0.049559,NaN
texture_se,-0.007526,-0.097317,0.386358,-0.086761,-0.066280,0.068406,0.046205,0.076218,0.021480,0.128053,...,0.409003,-0.102242,-0.083195,-0.073658,-0.092439,-0.068956,-0.119638,-0.128215,-0.045655,NaN
perimeter_se,0.137331,0.674172,0.281673,0.693135,0.726628,0.296092,0.548905,0.660391,0.710650,0.313893,...,0.200371,0.721031,0.730713,0.130054,0.341919,0.418899,0.554897,0.109930,0.085433,NaN
area_se,0.177742,0.735864,0.259845,0.744983,0.800086,0.246552,0.455653,0.617427,0.690299,0.223970,...,0.196497,0.761213,0.811408,0.125389,0.283257,0.385100,0.538166,0.074126,0.017539,NaN
smoothness_se,0.096781,-0.222600,0.006614,-0.202694,-0.166777,0.332375,0.135299,0.098564,0.027653,0.187321,...,-0.074743,-0.217304,-0.182195,0.314457,-0.055558,-0.058298,-0.102007,-0.107342,0.101480,NaN
compactness_se,0.033961,0.206000,0.191975,0.250744,0.212583,0.318943,0.738722,0.670279,0.490424,0.421659,...,0.143003,0.260516,0.199371,0.227394,0.678780,0.639147,0.483208,0.277878,0.590973,NaN
concavity_se,0.055239,0.194204,0.143293,0.228082,0.207660,0.248396,0.570517,0.691270,0.439167,0.342627,...,0.100241,0.226680,0.188353,0.168481,0.484858,0.662564,0.440472,0.197788,0.439329,NaN
concave points_se,0.078768,0.376169,0.163851,0.407217,0.372320,0.380676,0.642262,0.683260,0.615634,0.393298,...,0.086741,0.394999,0.342271,0.215351,0.452888,0.549592,0.602450,0.143116,0.310655,NaN
symmetry_se,-0.017306,-0.104321,0.009127,-0.081629,-0.072497,0.200774,0.229977,0.178009,0.095351,0.449137,...,-0.077473,-0.103753,-0.110343,-0.012662,0.060255,0.037119,-0.030413,0.389402,0.078079,NaN
fractal_dimension_se,0.025725,-0.042641,0.054458,-0.005523,-0.019887,0.283607,0.507318,0.449301,0.257584,0.331786,...,-0.003195,-0.001000,-0.022736,0.170568,0.390159,0.379975,0.215204,0.111094,0.591328,NaN
radius_worst,0.082405,0.969539,0.352573,0.969476,0.962746,0.213120,0.535315,0.688236,0.830318,0.185728,...,0.359921,0.993708,0.984015,0.216574,0.475820,0.573975,0.787424,0.243529,0.093492,NaN
texture_worst,0.064720,0.297008,0.912045,0.303038,0.287489,0.036072,0.248133,0.299879,0.292752,0.090651,...,1.000000,0.365098,0.345842,0.225429,0.360832,0.368366,0.359755,0.233027,0.219122,NaN
perimeter_worst,0.079986,0.965137,0.358040,0.970387,0.959120,0.238853,0.590210,0.729565,0.855923,0.219169,...,0.365098,1.000000,0.977578,0.236775,0.529408,0.618344,0.816322,0.269493,0.138957,NaN
area_worst,0.107187,0.941082,0.343546,0.941550,0.959213,0.206718,0.509604,0.675987,0.809630,0.177193,...,0.345842,0.977578,1.000000,0.209145,0.438296,0.543331,0.747419,0.209146,0.079647,NaN
smoothness_worst,0.010338,0.119616,0.077503,0.150549,0.123523,0.805324,0.565541,0.448822,0.452753,0.426675,...,0.225429,0.236775,0.209145,1.000000,0.568187,0.518523,0.547691,0.493838,0.617624,NaN
compactness_worst,-0.002968,0.413463,0.277830,0.455774,0.390410,0.472468,0.865809,0.754968,0.667454,0.473200,...,0.360832,0.529408,0.438296,0.568187,1.000000,0.892261,0.801080,0.614441,0.810455,NaN
concavity_worst,0.023203,0.526911,0.301025,0.563879,0.512606,0.434926,0.816275,0.884103,0.752399,0.433721,...,0.368366,0.618344,0.543331,0.518523,0.892261,1.000000,0.855434,0.532520,0.686511,NaN
concave points_worst,0.035174,0.744214,0.295316,0.771241,0.722017,0.503053,0.815573,0.861323,0.910155,0.430297,...,0.359755,0.816322,0.747419,0.547691,0.801080,0.855434,1.000000,0.502528,0.511114,NaN
symmetry_worst,-0.044224,0.163953,0.105008,0.189115,0.143570,0.394309,0.510223,0.409464,0.375744,0.699826,...,0.233027,0.269493,0.209146,0.493838,0.614441,0.532520,0.502528,1.000000,0.537848,NaN
fractal_dimension_worst,-0.029866,0.007066,0.119205,0.051019,0.003738,0.499316,0.687382,0.514930,0.368661,0.438413,...,0.219122,0.138957,0.079647,0.617624,0.810455,0.686511,0.511114,0.537848,1.000000,NaN
Unnamed: 32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [83]:
breast_ds.drop(['id','Unnamed: 32'],axis=1,inplace=True)

In [84]:
breast_ds.describe()

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
count,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,...,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000
mean,14.127292,19.289649,91.969033,654.889104,0.096360,0.104341,0.088799,0.048919,0.181162,0.062798,...,16.269190,25.677223,107.261213,880.583128,0.132369,0.254265,0.272188,0.114606,0.290076,0.083946
std,3.524049,4.301036,24.298981,351.914129,0.014064,0.052813,0.079720,0.038803,0.027414,0.007060,...,4.833242,6.146258,33.602542,569.356993,0.022832,0.157336,0.208624,0.065732,0.061867,0.018061
min,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,0.049960,...,7.930000,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040
25%,11.700000,16.170000,75.170000,420.300000,0.086370,0.064920,0.029560,0.020310,0.161900,0.057700,...,13.010000,21.080000,84.110000,515.300000,0.116600,0.147200,0.114500,0.064930,0.250400,0.071460
50%,13.370000,18.840000,86.240000,551.100000,0.095870,0.092630,0.061540,0.033500,0.179200,0.061540,...,14.970000,25.410000,97.660000,686.500000,0.131300,0.211900,0.226700,0.099930,0.282200,0.080040
75%,15.780000,21.800000,104.100000,782.700000,0.105300,0.130400,0.130700,0.074000,0.195700,0.066120,...,18.790000,29.720000,125.400000,1084.000000,0.146000,0.339100,0.382900,0.161400,0.317900,0.092080
max,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800,0.201200,0.304000,0.097440,...,36.040000,49.540000,251.200000,4254.000000,0.222600,1.058000,1.252000,0.291000,0.663800,0.207500

Encoding Target Column

In [85]:
from sklearn.preprocessing import LabelEncoder
LE=LabelEncoder()
breast_ds['diagnosis']=LE.fit_transform(breast_ds['diagnosis'])

In [86]:
breast_ds['diagnosis'].value_counts()

diagnosis
0    357
1    212
Name: count, dtype: int64

Splitting Data into train and test Sets

In [87]:
X=breast_ds.drop('diagnosis',axis=1)
y=breast_ds['diagnosis']

In [88]:
X.shape

(569, 30)

In [89]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [90]:
X_train.shape

(455, 30)

In [91]:
X_test.shape

(114, 30)

Feature Scaling

In [92]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [93]:
X_train

array([[-1.44075296, -0.43531947, -1.36208497, ...,  0.9320124 ,
         2.09724217,  1.88645014],
       [ 1.97409619,  1.73302577,  2.09167167, ...,  2.6989469 ,
         1.89116053,  2.49783848],
       [-1.39998202, -1.24962228, -1.34520926, ..., -0.97023893,
         0.59760192,  0.0578942 ],
       ...,
       [ 0.04880192, -0.55500086, -0.06512547, ..., -1.23903365,
        -0.70863864, -1.27145475],
       [-0.03896885,  0.10207345, -0.03137406, ...,  1.05001236,
         0.43432185,  1.21336207],
       [-0.54860557,  0.31327591, -0.60350155, ..., -0.61102866,
        -0.3345212 , -0.84628745]], shape=(455, 30))

In [94]:
X_test

array([[-0.46649743, -0.13728933, -0.44421138, ..., -0.19435087,
         0.17275669,  0.20372995],
       [ 1.36536344,  0.49866473,  1.30551088, ...,  0.99177862,
        -0.561211  , -1.00838949],
       [ 0.38006578,  0.06921974,  0.40410139, ...,  0.57035018,
        -0.10783139, -0.20629287],
       ...,
       [-0.73547237, -0.99852603, -0.74138839, ..., -0.27741059,
        -0.3820785 , -0.32408328],
       [ 0.02898271,  2.0334026 ,  0.0274851 , ..., -0.49027026,
        -1.60905688, -0.33137507],
       [ 1.87216885,  2.80077153,  1.80354992, ...,  0.7925579 ,
        -0.05868885, -0.09467243]], shape=(114, 30))

Prediction System

Selecting Top 10 Most Important Features

The app only asks the user for 10 measurements instead of all 30, so we rank every feature by importance and keep the top 10.

In [95]:
from sklearn.ensemble import RandomForestClassifier

ranker=RandomForestClassifier(n_estimators=300,random_state=42)
ranker.fit(X,y)

top_features=pd.Series(ranker.feature_importances_,index=X.columns).sort_values(ascending=False).head(10).index.tolist()
top_features

['perimeter_worst',
 'area_worst',
 'concave points_worst',
 'concave points_mean',
 'radius_worst',
 'perimeter_mean',
 'concavity_mean',
 'radius_mean',
 'area_mean',
 'concavity_worst']

Training the Final Model on the Top 10 Features

In [96]:
X_top=X[top_features]

X_top_train,X_top_test,y_top_train,y_top_test=train_test_split(X_top,y,test_size=0.2,random_state=42)

final_scaler=StandardScaler()
X_top_train=final_scaler.fit_transform(X_top_train)
X_top_test=final_scaler.transform(X_top_test)

final_model=LogisticRegression(max_iter=5000)
final_model.fit(X_top_train,y_top_train)

final_accuracy=accuracy_score(y_top_test,final_model.predict(X_top_test))
final_accuracy

0.9736842105263158

Building "Usual Range" Hints for the App

For each of the 10 selected features, work out a friendly, rounded range (e.g. 0-40) close to but a bit wider than the actual data range, so it reads as a helpful guide rather than a strict data boundary.

In [97]:
import math

def nice_upper_bound(x):
    """Round x up to a 'nice' looking number (40, 200, 3000, 0.3, ...)."""
    if x <= 0:
        return 1.0
    magnitude = 10 ** math.floor(math.log10(x))
    for m in [1, 1.5, 2, 3, 4, 5, 7, 10]:
        candidate = round(m * magnitude, 10)
        if candidate >= x:
            return float(candidate)
    return float(10 * magnitude)

def build_field_stats(df):
    stats={}
    for col in df.columns:
        col_min,col_max,col_median=df[col].min(),df[col].max(),df[col].median()
        value_range=max(col_max-col_min,1e-9)
        step=float(10**(math.floor(math.log10(value_range))-2))
        decimals=max(0,int(-math.floor(math.log10(step))))
        stats[col]={
            'min':0.0,
            'max':nice_upper_bound(col_max),
            'default':float(round(col_median,decimals)),
            'step':step,
            'decimals':decimals,
        }
    return stats

field_stats=build_field_stats(X_top)
field_stats

{'perimeter_worst': {'min': 0.0,
  'max': 300.0,
  'default': 98.0,
  'step': 1.0,
  'decimals': 0},
 'area_worst': {'min': 0.0,
  'max': 5000.0,
  'default': 686.0,
  'step': 10.0,
  'decimals': 0},
 'concave points_worst': {'min': 0.0,
  'max': 0.3,
  'default': 0.1,
  'step': 0.001,
  'decimals': 3},
 'concave points_mean': {'min': 0.0,
  'max': 0.3,
  'default': 0.034,
  'step': 0.001,
  'decimals': 3},
 'radius_worst': {'min': 0.0,
  'max': 40.0,
  'default': 15.0,
  'step': 0.1,
  'decimals': 1},
 'perimeter_mean': {'min': 0.0,
  'max': 200.0,
  'default': 86.0,
  'step': 1.0,
  'decimals': 0},
 'concavity_mean': {'min': 0.0,
  'max': 0.5,
  'default': 0.062,
  'step': 0.001,
  'decimals': 3},
 'radius_mean': {'min': 0.0,
  'max': 30.0,
  'default': 13.4,
  'step': 0.1,
  'decimals': 1},
 'area_mean': {'min': 0.0,
  'max': 3000.0,
  'default': 551.0,
  'step': 10.0,
  'decimals': 0},
 'concavity_worst': {'min': 0.0,
  'max': 1.5,
  'default': 0.23,
  'step': 0.01,
  'decimals': 2}}

Exporting Model Artifacts for the Streamlit App

Saves the trained model, scaler, selected feature names, and slider ranges so `app.py` can load them without retraining.

In [98]:
import joblib

joblib.dump(final_model,'model.pkl')
joblib.dump(final_scaler,'scaler.pkl')
joblib.dump(top_features,'feature_names.pkl')
joblib.dump(field_stats,'feature_stats.pkl')
print('Saved model.pkl, scaler.pkl, feature_names.pkl, feature_stats.pkl')

Saved model.pkl, scaler.pkl, feature_names.pkl, feature_stats.pkl